import sqlite3

conn = sqlite3.connect("database.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company TEXT,
    question TEXT,
    skill TEXT,
    difficulty TEXT
)
""")



# 🔥 ADD MORE QUESTIONS
questions = [

# ---------------- DSA (40) ----------------
("Google", "Explain binary search and its time complexity.", "dsa", "easy"),
("Google", "What is linear search?", "dsa", "easy"),
("Google", "Explain recursion with example.", "dsa", "easy"),
("Google", "What is a stack?", "dsa", "easy"),
("Google", "What is a queue?", "dsa", "easy"),
("Google", "Explain linked list.", "dsa", "easy"),
("Google", "What is a tree data structure?", "dsa", "easy"),
("Google", "Explain graph basics.", "dsa", "easy"),

("Google", "Explain DFS and BFS.", "dsa", "medium"),
("Google", "What is dynamic programming?", "dsa", "medium"),
("Google", "Explain merge sort.", "dsa", "medium"),
("Google", "Explain quick sort.", "dsa", "medium"),
("Google", "What is a heap?", "dsa", "medium"),
("Google", "Explain hashing.", "dsa", "medium"),
("Google", "What is collision in hashing?", "dsa", "medium"),
("Google", "Explain two pointer technique.", "dsa", "medium"),
("Google", "What is sliding window?", "dsa", "medium"),

("Google", "Explain Dijkstra algorithm.", "dsa", "hard"),
("Google", "Explain Floyd Warshall algorithm.", "dsa", "hard"),
("Google", "What is backtracking?", "dsa", "hard"),
("Google", "Explain NP-complete problems.", "dsa", "hard"),
("Google", "Explain segment trees.", "dsa", "hard"),
("Google", "Explain trie data structure.", "dsa", "hard"),
("Google", "What is topological sorting?", "dsa", "hard"),
("Google", "Explain KMP algorithm.", "dsa", "hard"),

# ---------------- SYSTEM DESIGN (20) ----------------
("Google", "Design a URL shortener like bit.ly.", "system design", "medium"),
("Google", "Design a chat application.", "system design", "medium"),
("Google", "What is load balancing?", "system design", "easy"),
("Google", "Explain caching.", "system design", "medium"),
("Google", "What is scalability?", "system design", "easy"),
("Google", "Design a notification system.", "system design", "medium"),
("Google", "Explain database sharding.", "system design", "hard"),
("Google", "Design YouTube architecture.", "system design", "hard"),
("Google", "Design Twitter feed system.", "system design", "hard"),
("Google", "What is CDN?", "system design", "medium"),

# ---------------- DBMS (15) ----------------
("Google", "What is DBMS?", "dbms", "easy"),
("Google", "Explain normalization.", "dbms", "easy"),
("Google", "What is SQL?", "dbms", "easy"),
("Google", "Difference between SQL and NoSQL.", "dbms", "easy"),
("Google", "Explain joins.", "dbms", "medium"),
("Google", "What is indexing?", "dbms", "medium"),
("Google", "Explain transactions.", "dbms", "medium"),
("Google", "What is ACID?", "dbms", "medium"),
("Google", "Explain deadlock in DB.", "dbms", "hard"),

# ---------------- OS (10) ----------------
("Google", "What is operating system?", "os", "easy"),
("Google", "Explain process vs thread.", "os", "easy"),
("Google", "What is deadlock?", "os", "medium"),
("Google", "Explain paging.", "os", "medium"),
("Google", "What is scheduling?", "os", "medium"),
("Google", "Explain virtual memory.", "os", "medium"),

# ---------------- HR (15) ----------------
("Google", "Tell me about yourself.", "hr", "easy"),
("Google", "Why Google?", "hr", "easy"),
("Google", "Describe a challenge you faced.", "hr", "medium"),
("Google", "What are your strengths?", "hr", "easy"),
("Google", "What are your weaknesses?", "hr", "easy"),
("Google", "Where do you see yourself in 5 years?", "hr", "medium"),
("Google", "Why should we hire you?", "hr", "medium"),
("Google", "Describe teamwork experience.", "hr", "easy"),
("Google", "Tell me about a failure.", "hr", "medium"),
("Google", "How do you handle pressure?", "hr", "medium"),

# --------------------Networking --------------------------
("Google", "What is the OSI model? Explain all 7 layers.", "networking", "easy"),
("Google", "Difference between TCP and UDP  ", "networking", "easy"),
("Google", " What is an IP address? Types of IP addresses. ", "networking", "easy"),
("Google", "What is DNS and how does it work?  ", "networking", "easy"),
("Google", "What happens when you type a URL in the browser?  ", "networking", "easy"),
("Google", " What is the difference between HTTP and HTTPS? ", "networking", "medium"),
("Google", "Explain three-way handshake in TCP.  ", "networking", "medium"),
("Google", "What is subnetting and why is it used?  ", "networking", "medium"),
("Google", " What is NAT (Network Address Translation)? ", "networking", "medium"),
("Google", "Difference between hub, switch, and router.  ", "networking", "medium"),
("Google", " What is load balancing? Types of load balancers. ", "networking", "hard"),
("Google", "What is latency vs bandwidth?  ", "networking", "hard"),
("Google", " How does CDN (Content Delivery Network) work? ", "networking", "hard"),
("Google", " What is packet loss and how do you reduce it? ", "networking", "hard"),
("Google", "How would you design a highly scalable network system?  ", "networking", "hard"),


# ---------------- HR / LEADERSHIP (25) ----------------
("Amazon", "Tell me about yourself.", "hr", "easy"),
("Amazon", "Why do you want to work at Amazon?", "hr", "easy"),
("Amazon", "Explain Amazon leadership principles.", "hr", "easy"),
("Amazon", "Tell me about a time you showed ownership.", "hr", "medium"),
("Amazon", "Describe a failure and what you learned.", "hr", "medium"),
("Amazon", "Tell me about a time you disagreed with a team member.", "hr", "medium"),
("Amazon", "Describe a challenging situation you handled.", "hr", "medium"),
("Amazon", "Tell me about a time you delivered under pressure.", "hr", "medium"),
("Amazon", "What are your strengths?", "hr", "easy"),
("Amazon", "What are your weaknesses?", "hr", "easy"),
("Amazon", "Tell me about a time you took initiative.", "hr", "medium"),
("Amazon", "Describe a situation where you failed to meet a deadline.", "hr", "medium"),
("Amazon", "How do you handle criticism?", "hr", "medium"),
("Amazon", "Tell me about a time you improved a process.", "hr", "medium"),
("Amazon", "Describe a situation where you solved a problem creatively.", "hr", "medium"),
("Amazon", "Tell me about a time you worked in a team.", "hr", "easy"),
("Amazon", "Describe a conflict and how you resolved it.", "hr", "medium"),
("Amazon", "Tell me about a time you had to learn something quickly.", "hr", "medium"),
("Amazon", "Describe a leadership experience.", "hr", "medium"),
("Amazon", "Tell me about a time you handled ambiguity.", "hr", "hard"),
("Amazon", "How do you prioritize tasks?", "hr", "easy"),
("Amazon", "Describe a time you went above and beyond.", "hr", "medium"),
("Amazon", "Tell me about a time you failed and recovered.", "hr", "medium"),
("Amazon", "Why should we hire you?", "hr", "easy"),
("Amazon", "Where do you see yourself in 5 years?", "hr", "easy"),
("Amazon", "Amazon Prime subscriptions are decreasing—how would you investigate?", "hr", "hard"),
("Amazon", "How would you analyze cart abandonment rate?", "hr", "hard"),
("Amazon", "How would you optimize pricing strategy for a product?", "hr", "hard"),
("Amazon", "How would you decide whether to launch a feature globally or not?", "hr", "hard"),


# ---------------- DSA (30) ----------------
("Amazon", "Explain binary search.", "dsa", "easy"),
("Amazon", "What is a stack?", "dsa", "easy"),
("Amazon", "What is a queue?", "dsa", "easy"),
("Amazon", "Explain linked list.", "dsa", "easy"),
("Amazon", "What is a tree?", "dsa", "easy"),
("Amazon", "Explain graph basics.", "dsa", "easy"),
("Amazon", "Explain BFS and DFS.", "dsa", "medium"),
("Amazon", "What is recursion?", "dsa", "easy"),
("Amazon", "Explain merge sort.", "dsa", "medium"),
("Amazon", "Explain quick sort.", "dsa", "medium"),
("Amazon", "What is hashing?", "dsa", "medium"),
("Amazon", "What is collision in hashing?", "dsa", "medium"),
("Amazon", "Explain sliding window technique.", "dsa", "medium"),
("Amazon", "Explain two pointer technique.", "dsa", "medium"),
("Amazon", "What is dynamic programming?", "dsa", "medium"),
("Amazon", "Explain memoization.", "dsa", "medium"),
("Amazon", "What is a heap?", "dsa", "medium"),
("Amazon", "Explain priority queue.", "dsa", "medium"),
("Amazon", "Explain topological sorting.", "dsa", "hard"),
("Amazon", "Explain Dijkstra algorithm.", "dsa", "hard"),
("Amazon", "Explain backtracking.", "dsa", "hard"),
("Amazon", "What is greedy algorithm?", "dsa", "medium"),
("Amazon", "Explain Kadane’s algorithm.", "dsa", "medium"),
("Amazon", "Explain longest common subsequence.", "dsa", "hard"),
("Amazon", "Explain knapsack problem.", "dsa", "hard"),
("Amazon", "Detect cycle in graph.", "dsa", "hard"),
("Amazon", "Find shortest path in graph.", "dsa", "hard"),
("Amazon", "Reverse a linked list.", "dsa", "easy"),
("Amazon", "Find middle of linked list.", "dsa", "easy"),
("Amazon", "Check if string is palindrome.", "dsa", "easy"),

# ---------------- SYSTEM DESIGN (20) ----------------
("Amazon", "Design a URL shortener.", "system design", "medium"),
("Amazon", "Design an e-commerce system.", "system design", "medium"),
("Amazon", "Design a chat application.", "system design", "medium"),
("Amazon", "Explain load balancing.", "system design", "easy"),
("Amazon", "What is caching?", "system design", "medium"),
("Amazon", "Design a notification system.", "system design", "medium"),
("Amazon", "Design Amazon product search.", "system design", "hard"),
("Amazon", "Explain microservices architecture.", "system design", "medium"),
("Amazon", "What is API gateway?", "system design", "medium"),
("Amazon", "Explain database sharding.", "system design", "hard"),
("Amazon", "Design a logging system.", "system design", "medium"),
("Amazon", "Design a file storage system.", "system design", "hard"),
("Amazon", "Explain CAP theorem.", "system design", "hard"),
("Amazon", "What is eventual consistency?", "system design", "medium"),
("Amazon", "Design a recommendation system.", "system design", "hard"),
("Amazon", "Explain CDN.", "system design", "medium"),
("Amazon", "Design a queue system.", "system design", "medium"),
("Amazon", "Explain rate limiting.", "system design", "medium"),
("Amazon", "Design a payment system.", "system design", "hard"),
("Amazon", "Explain scalability.", "system design", "easy"),

# ---------------- DBMS (15) ----------------
("Amazon", "What is DBMS?", "dbms", "easy"),
("Amazon", "Explain normalization.", "dbms", "easy"),
("Amazon", "What is SQL?", "dbms", "easy"),
("Amazon", "Difference between SQL and NoSQL.", "dbms", "easy"),
("Amazon", "Explain joins.", "dbms", "medium"),
("Amazon", "What is indexing?", "dbms", "medium"),
("Amazon", "Explain ACID properties.", "dbms", "medium"),
("Amazon", "What is transaction?", "dbms", "medium"),
("Amazon", "Explain deadlock.", "dbms", "hard"),
("Amazon", "What is primary key?", "dbms", "easy"),
("Amazon", "Write a SQL query to find the top 5 selling products.", "dbms", "easy"),
("Amazon", "What is view?", "dbms", "easy"),
("Amazon", "Explain stored procedures.", "dbms", "medium"),
("Amazon", "What is normalization vs denormalization?", "dbms", "medium"),
("Amazon", "Explain indexing types.", "dbms", "hard"),
("Amazon", "How do you calculate conversion rate?", "dbms", "hard"),
# ---------------- OS (10) ----------------
("Amazon", "What is operating system?", "os", "easy"),
("Amazon", "Explain process vs thread.", "os", "easy"),
("Amazon", "What is deadlock?", "os", "medium"),
("Amazon", "Explain scheduling algorithms.", "os", "medium"),
("Amazon", "What is paging?", "os", "medium"),
("Amazon", "Explain virtual memory.", "os", "medium"),
("Amazon", "What is semaphore?", "os", "hard"),
("Amazon", "Explain mutex.", "os", "medium"),
("Amazon", "What is context switching?", "os", "medium"),
("Amazon", "Explain memory management.", "os", "medium"),



# ----------------microsoft HR (20) ----------------
("Microsoft", "Tell me about yourself.", "hr", "easy"),
("Microsoft", "Why Microsoft?", "hr", "easy"),
("Microsoft", "Describe a project you worked on.", "hr", "easy"),
("Microsoft", "What are your strengths?", "hr", "easy"),
("Microsoft", "What are your weaknesses?", "hr", "easy"),
("Microsoft", "Tell me about a challenge you faced.", "hr", "medium"),
("Microsoft", "Describe teamwork experience.", "hr", "easy"),
("Microsoft", "Tell me about a failure.", "hr", "medium"),
("Microsoft", "How do you handle deadlines?", "hr", "medium"),
("Microsoft", "Why should we hire you?", "hr", "easy"),
("Microsoft", "Where do you see yourself in 5 years?", "hr", "easy"),
("Microsoft", "Describe leadership experience.", "hr", "medium"),
("Microsoft", "Tell me about a conflict and resolution.", "hr", "medium"),
("Microsoft", "What motivates you?", "hr", "easy"),
("Microsoft", "How do you learn new technologies?", "hr", "medium"),
("Microsoft", "Describe a time you solved a problem.", "hr", "medium"),
("Microsoft", "Tell me about your biggest achievement.", "hr", "easy"),
("Microsoft", "How do you handle pressure?", "hr", "medium"),
("Microsoft", "Tell me about a time you improved something.", "hr", "medium"),
("Microsoft", "Describe a difficult decision you made.", "hr", "medium"),

# ---------------- OOP (25) ----------------
("Microsoft", "What is Object-Oriented Programming?", "oop", "easy"),
("Microsoft", "Explain the four pillars of OOP.", "oop", "easy"),
("Microsoft", "What is inheritance?", "oop", "easy"),
("Microsoft", "Explain polymorphism.", "oop", "medium"),
("Microsoft", "What is encapsulation?", "oop", "easy"),
("Microsoft", "Explain abstraction.", "oop", "medium"),
("Microsoft", "What is method overloading?", "oop", "easy"),
("Microsoft", "What is method overriding?", "oop", "easy"),
("Microsoft", "Difference between overloading and overriding.", "oop", "medium"),
("Microsoft", "What is an interface?", "oop", "medium"),
("Microsoft", "What is an abstract class?", "oop", "medium"),
("Microsoft", "Interface vs abstract class.", "oop", "medium"),
("Microsoft", "What is constructor?", "oop", "easy"),
("Microsoft", "Explain constructor overloading.", "oop", "medium"),
("Microsoft", "What is static keyword?", "oop", "easy"),
("Microsoft", "What is this keyword?", "oop", "easy"),
("Microsoft", "What is super keyword?", "oop", "medium"),
("Microsoft", "Explain access modifiers.", "oop", "easy"),
("Microsoft", "What is composition?", "oop", "medium"),
("Microsoft", "What is aggregation?", "oop", "medium"),
("Microsoft", "Composition vs inheritance.", "oop", "hard"),
("Microsoft", "What is SOLID principles?", "oop", "hard"),
("Microsoft", "Explain design patterns.", "oop", "hard"),
("Microsoft", "What is dependency injection?", "oop", "hard"),
("Microsoft", "What is coupling and cohesion?", "oop", "medium"),

# ---------------- DBMS (20) ----------------
("Microsoft", "What is DBMS?", "dbms", "easy"),
("Microsoft", "Explain normalization.", "dbms", "easy"),
("Microsoft", "What is SQL?", "dbms", "easy"),
("Microsoft", "Difference between SQL and NoSQL.", "dbms", "easy"),
("Microsoft", "Explain joins.", "dbms", "medium"),
("Microsoft", "Types of joins.", "dbms", "medium"),
("Microsoft", "What is indexing?", "dbms", "medium"),
("Microsoft", "Explain primary key.", "dbms", "easy"),
("Microsoft", "What is foreign key?", "dbms", "easy"),
("Microsoft", "What is a view?", "dbms", "easy"),
("Microsoft", "Explain ACID properties.", "dbms", "medium"),
("Microsoft", "What is transaction?", "dbms", "medium"),
("Microsoft", "Explain deadlock.", "dbms", "hard"),
("Microsoft", "What is normalization vs denormalization?", "dbms", "medium"),
("Microsoft", "Explain indexing types.", "dbms", "hard"),
("Microsoft", "What is stored procedure?", "dbms", "medium"),
("Microsoft", "What is trigger?", "dbms", "medium"),
("Microsoft", "Explain constraints.", "dbms", "easy"),
("Microsoft", "What is schema?", "dbms", "easy"),
("Microsoft", "Explain ER diagram.", "dbms", "medium"),

# ---------------- DSA (20) ----------------
("Microsoft", "Explain binary search.", "dsa", "easy"),
("Microsoft", "What is linked list?", "dsa", "easy"),
("Microsoft", "Explain stack and queue.", "dsa", "easy"),
("Microsoft", "What is tree?", "dsa", "easy"),
("Microsoft", "Explain graph basics.", "dsa", "easy"),
("Microsoft", "Explain BFS and DFS.", "dsa", "medium"),
("Microsoft", "What is recursion?", "dsa", "easy"),
("Microsoft", "Explain merge sort.", "dsa", "medium"),
("Microsoft", "Explain quick sort.", "dsa", "medium"),
("Microsoft", "What is hashing?", "dsa", "medium"),
("Microsoft", "Explain sliding window.", "dsa", "medium"),
("Microsoft", "Explain two pointer technique.", "dsa", "medium"),
("Microsoft", "What is dynamic programming?", "dsa", "medium"),
("Microsoft", "Explain memoization.", "dsa", "medium"),
("Microsoft", "What is heap?", "dsa", "medium"),
("Microsoft", "Explain priority queue.", "dsa", "medium"),
("Microsoft", "Reverse a linked list.", "dsa", "easy"),
("Microsoft", "Find middle of linked list.", "dsa", "easy"),
("Microsoft", "Check palindrome string.", "dsa", "easy"),
("Microsoft", "Detect cycle in linked list.", "dsa", "medium"),

# ---------------- OS (15) ----------------
("Microsoft", "What is operating system?", "os", "easy"),
("Microsoft", "Explain process vs thread.", "os", "easy"),
("Microsoft", "What is deadlock?", "os", "medium"),
("Microsoft", "Explain scheduling algorithms.", "os", "medium"),
("Microsoft", "What is paging?", "os", "medium"),
("Microsoft", "Explain virtual memory.", "os", "medium"),
("Microsoft", "What is semaphore?", "os", "hard"),
("Microsoft", "Explain mutex.", "os", "medium"),
("Microsoft", "What is context switching?", "os", "medium"),
("Microsoft", "Explain memory management.", "os", "medium"),
("Microsoft", "What is fragmentation?", "os", "medium"),
("Microsoft", "Explain multi-threading.", "os", "medium"),
("Microsoft", "What is starvation?", "os", "hard"),
("Microsoft", "Explain scheduling types.", "os", "medium"),
("Microsoft", "What is IPC?", "os", "medium"),


# ---------------- HR (20) ----------------
("TCS", "Tell me about yourself.", "hr", "easy"),
("TCS", "Why do you want to join TCS?", "hr", "easy"),
("TCS", "What are your strengths?", "hr", "easy"),
("TCS", "What are your weaknesses?", "hr", "easy"),
("TCS", "Where do you see yourself in 5 years?", "hr", "easy"),
("TCS", "Why should we hire you?", "hr", "easy"),
("TCS", "Tell me about your project.", "hr", "easy"),
("TCS", "Describe a challenge you faced.", "hr", "medium"),
("TCS", "Tell me about teamwork experience.", "hr", "easy"),
("TCS", "How do you handle pressure?", "hr", "medium"),
("TCS", "Tell me about a failure.", "hr", "medium"),
("TCS", "Are you willing to relocate?", "hr", "easy"),
("TCS", "What motivates you?", "hr", "easy"),
("TCS", "Describe leadership experience.", "hr", "medium"),
("TCS", "Tell me about your biggest achievement.", "hr", "easy"),
("TCS", "How do you manage time?", "hr", "easy"),
("TCS", "Tell me about a conflict and resolution.", "hr", "medium"),
("TCS", "Why IT industry?", "hr", "easy"),
("TCS", "What are your career goals?", "hr", "easy"),
("TCS", "Are you comfortable working in shifts?", "hr", "easy"),

# ---------------- JAVA (30) ----------------
("TCS", "What is Java?", "java", "easy"),
("TCS", "Explain JVM.", "java", "easy"),
("TCS", "What is JDK and JRE?", "java", "easy"),
("TCS", "Explain OOP in Java.", "java", "easy"),
("TCS", "What is inheritance in Java?", "java", "easy"),
("TCS", "Explain polymorphism in Java.", "java", "medium"),
("TCS", "What is encapsulation?", "java", "easy"),
("TCS", "What is abstraction?", "java", "medium"),
("TCS", "What is constructor?", "java", "easy"),
("TCS", "Explain constructor overloading.", "java", "medium"),
("TCS", "What is method overloading?", "java", "easy"),
("TCS", "What is method overriding?", "java", "easy"),
("TCS", "Difference between overloading and overriding.", "java", "medium"),
("TCS", "What is interface in Java?", "java", "medium"),
("TCS", "What is abstract class?", "java", "medium"),
("TCS", "Interface vs abstract class.", "java", "medium"),
("TCS", "What is exception handling?", "java", "easy"),
("TCS", "Types of exceptions.", "java", "medium"),
("TCS", "What is try-catch block?", "java", "easy"),
("TCS", "What is finally block?", "java", "easy"),
("TCS", "What is multithreading?", "java", "medium"),
("TCS", "What is synchronization?", "java", "medium"),
("TCS", "What is String class?", "java", "easy"),
("TCS", "Difference between String and StringBuilder.", "java", "medium"),
("TCS", "What is collection framework?", "java", "medium"),
("TCS", "Explain ArrayList.", "java", "easy"),
("TCS", "Explain HashMap.", "java", "medium"),
("TCS", "What is garbage collection?", "java", "medium"),
("TCS", "What is static keyword?", "java", "easy"),
("TCS", "What is final keyword?", "java", "easy"),

# ---------------- DBMS / SQL (20) ----------------
("TCS", "What is DBMS?", "dbms", "easy"),
("TCS", "What is SQL?", "sql", "easy"),
("TCS", "Explain normalization.", "dbms", "easy"),
("TCS", "What are joins?", "sql", "medium"),
("TCS", "Types of joins.", "sql", "medium"),
("TCS", "What is primary key?", "dbms", "easy"),
("TCS", "What is foreign key?", "dbms", "easy"),
("TCS", "What is indexing?", "dbms", "medium"),
("TCS", "Difference between SQL and NoSQL.", "dbms", "easy"),
("TCS", "What is view?", "dbms", "easy"),
("TCS", "Explain ACID properties.", "dbms", "medium"),
("TCS", "What is transaction?", "dbms", "medium"),
("TCS", "What is stored procedure?", "dbms", "medium"),
("TCS", "What is trigger?", "dbms", "medium"),
("TCS", "Explain constraints.", "dbms", "easy"),
("TCS", "What is schema?", "dbms", "easy"),
("TCS", "Explain ER diagram.", "dbms", "medium"),
("TCS", "What is normalization vs denormalization?", "dbms", "medium"),
("TCS", "What is indexing type?", "dbms", "hard"),
("TCS", "Explain database architecture.", "dbms", "medium"),

# ---------------- APTITUDE / BASICS (15) ----------------
("TCS", "What is percentage?", "aptitude", "easy"),
("TCS", "Explain profit and loss.", "aptitude", "easy"),
("TCS", "What is time and work?", "aptitude", "easy"),
("TCS", "Explain ratio and proportion.", "aptitude", "easy"),
("TCS", "What is speed, time and distance?", "aptitude", "easy"),
("TCS", "What is simple interest?", "aptitude", "easy"),
("TCS", "What is compound interest?", "aptitude", "medium"),
("TCS", "Solve basic algebra equation.", "aptitude", "easy"),
("TCS", "What is probability?", "aptitude", "medium"),
("TCS", "Explain permutations and combinations.", "aptitude", "medium"),
("TCS", "What is logical reasoning?", "aptitude", "easy"),
("TCS", "Solve number series.", "aptitude", "medium"),
("TCS", "Solve coding-decoding problem.", "aptitude", "medium"),
("TCS", "What is blood relation problem?", "aptitude", "easy"),
("TCS", "Explain direction sense problem.", "aptitude", "easy"),

# ---------------- BASIC CS (15) ----------------
("TCS", "What is computer network?", "networking", "easy"),
("TCS", "Explain OS basics.", "os", "easy"),
("TCS", "What is process?", "os", "easy"),
("TCS", "What is thread?", "os", "easy"),
("TCS", "Difference between process and thread.", "os", "medium"),
("TCS", "What is deadlock?", "os", "medium"),
("TCS", "Explain scheduling.", "os", "medium"),
("TCS", "What is paging?", "os", "medium"),
("TCS", "Explain memory management.", "os", "medium"),
("TCS", "What is IP address?", "networking", "easy"),
("TCS", "What is HTTP?", "networking", "easy"),
("TCS", "Explain DNS.", "networking", "medium"),
("TCS", "What is firewall?", "networking", "easy"),
("TCS", "Explain TCP vs UDP.", "networking", "medium"),
("TCS", "What is cloud computing?", "networking", "easy"),


# ---------------- HR (20) ----------------
("Infosys", "Tell me about yourself.", "hr", "easy"),
("Infosys", "Why do you want to join Infosys?", "hr", "easy"),
("Infosys", "What are your strengths?", "hr", "easy"),
("Infosys", "What are your weaknesses?", "hr", "easy"),
("Infosys", "Where do you see yourself in 5 years?", "hr", "easy"),
("Infosys", "Why should we hire you?", "hr", "easy"),
("Infosys", "Tell me about your project.", "hr", "easy"),
("Infosys", "Describe a challenge you faced.", "hr", "medium"),
("Infosys", "Tell me about teamwork experience.", "hr", "easy"),
("Infosys", "How do you handle pressure?", "hr", "medium"),
("Infosys", "Tell me about a failure.", "hr", "medium"),
("Infosys", "Are you willing to relocate?", "hr", "easy"),
("Infosys", "What motivates you?", "hr", "easy"),
("Infosys", "Describe leadership experience.", "hr", "medium"),
("Infosys", "Tell me about your biggest achievement.", "hr", "easy"),
("Infosys", "How do you manage time?", "hr", "easy"),
("Infosys", "Tell me about a conflict and resolution.", "hr", "medium"),
("Infosys", "Why IT industry?", "hr", "easy"),
("Infosys", "What are your career goals?", "hr", "easy"),
("Infosys", "Are you comfortable working in shifts?", "hr", "easy"),

# ---------------- PYTHON (30) ----------------
("Infosys", "What is Python?", "python", "easy"),
("Infosys", "Features of Python.", "python", "easy"),
("Infosys", "What are data types in Python?", "python", "easy"),
("Infosys", "What is a list?", "python", "easy"),
("Infosys", "What is a tuple?", "python", "easy"),
("Infosys", "List vs tuple.", "python", "easy"),
("Infosys", "What is dictionary?", "python", "easy"),
("Infosys", "What is set in Python?", "python", "easy"),
("Infosys", "Explain loops in Python.", "python", "easy"),
("Infosys", "What is function in Python?", "python", "easy"),
("Infosys", "What is lambda function?", "python", "medium"),
("Infosys", "What is list comprehension?", "python", "medium"),
("Infosys", "Explain OOP in Python.", "python", "medium"),
("Infosys", "What is inheritance in Python?", "python", "medium"),
("Infosys", "What is polymorphism in Python?", "python", "medium"),
("Infosys", "What is encapsulation?", "python", "medium"),
("Infosys", "What is abstraction?", "python", "medium"),
("Infosys", "What is exception handling?", "python", "easy"),
("Infosys", "What is try-except?", "python", "easy"),
("Infosys", "What is finally block?", "python", "easy"),
("Infosys", "What is file handling?", "python", "medium"),
("Infosys", "Explain modules and packages.", "python", "medium"),
("Infosys", "What is pip?", "python", "easy"),
("Infosys", "What is virtual environment?", "python", "medium"),
("Infosys", "What is recursion?", "python", "medium"),
("Infosys", "What is generator?", "python", "medium"),
("Infosys", "What is iterator?", "python", "medium"),
("Infosys", "Difference between deep copy and shallow copy.", "python", "hard"),
("Infosys", "What is GIL?", "python", "hard"),
("Infosys", "What is multithreading in Python?", "python", "medium"),

# ---------------- DBMS / SQL (20) ----------------
("Infosys", "What is DBMS?", "dbms", "easy"),
("Infosys", "What is SQL?", "sql", "easy"),
("Infosys", "Explain normalization.", "dbms", "easy"),
("Infosys", "What are joins?", "sql", "medium"),
("Infosys", "Types of joins.", "sql", "medium"),
("Infosys", "What is primary key?", "dbms", "easy"),
("Infosys", "What is foreign key?", "dbms", "easy"),
("Infosys", "What is indexing?", "dbms", "medium"),
("Infosys", "Difference between SQL and NoSQL.", "dbms", "easy"),
("Infosys", "What is view?", "dbms", "easy"),
("Infosys", "Explain ACID properties.", "dbms", "medium"),
("Infosys", "What is transaction?", "dbms", "medium"),
("Infosys", "What is stored procedure?", "dbms", "medium"),
("Infosys", "What is trigger?", "dbms", "medium"),
("Infosys", "Explain constraints.", "dbms", "easy"),
("Infosys", "What is schema?", "dbms", "easy"),
("Infosys", "Explain ER diagram.", "dbms", "medium"),
("Infosys", "What is normalization vs denormalization?", "dbms", "medium"),
("Infosys", "What is indexing type?", "dbms", "hard"),
("Infosys", "Explain database architecture.", "dbms", "medium"),

# ---------------- APTITUDE / LOGIC (15) ----------------
("Infosys", "What is percentage?", "aptitude", "easy"),
("Infosys", "Explain profit and loss.", "aptitude", "easy"),
("Infosys", "What is time and work?", "aptitude", "easy"),
("Infosys", "Explain ratio and proportion.", "aptitude", "easy"),
("Infosys", "What is speed, time and distance?", "aptitude", "easy"),
("Infosys", "What is simple interest?", "aptitude", "easy"),
("Infosys", "What is compound interest?", "aptitude", "medium"),
("Infosys", "Solve basic algebra equation.", "aptitude", "easy"),
("Infosys", "What is probability?", "aptitude", "medium"),
("Infosys", "Explain permutations and combinations.", "aptitude", "medium"),
("Infosys", "Solve number series.", "aptitude", "medium"),
("Infosys", "Solve coding-decoding problem.", "aptitude", "medium"),
("Infosys", "Explain logical reasoning basics.", "aptitude", "easy"),
("Infosys", "What is blood relation problem?", "aptitude", "easy"),
("Infosys", "Explain direction sense problem.", "aptitude", "easy"),

# ---------------- BASIC CS (15) ----------------
("Infosys", "What is operating system?", "os", "easy"),
("Infosys", "Explain process vs thread.", "os", "easy"),
("Infosys", "What is deadlock?", "os", "medium"),
("Infosys", "Explain scheduling algorithms.", "os", "medium"),
("Infosys", "What is paging?", "os", "medium"),
("Infosys", "Explain virtual memory.", "os", "medium"),
("Infosys", "What is semaphore?", "os", "hard"),
("Infosys", "Explain mutex.", "os", "medium"),
("Infosys", "What is context switching?", "os", "medium"),
("Infosys", "Explain memory management.", "os", "medium"),
("Infosys", "What is computer network?", "networking", "easy"),
("Infosys", "What is IP address?", "networking", "easy"),
("Infosys", "Explain DNS.", "networking", "medium"),
("Infosys", "What is HTTP?", "networking", "easy"),
("Infosys", "Explain TCP vs UDP.", "networking", "medium"),


]
cursor.execute("DELETE FROM questions")
cursor.executemany("""
INSERT INTO questions (company, question, skill, difficulty)
VALUES (?, ?, ?, ?)
""", questions)

# USERS TABLE
cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    email TEXT UNIQUE,
    password TEXT
)
""")


# pdf save on dashboard
cursor.execute("""
CREATE TABLE IF NOT EXISTS resumes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    template TEXT,
    resume_html TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
""")

conn.commit()
conn.close()

print("✅ Database updated with questions!")
print("Users table created")
print("Database and table created successfully!")